-- =============================================================================
-- V1: initial ledger schema (Flyway)
-- Portable SQL: runs on PostgreSQL 15 (prod/dev) and H2 in PostgreSQL mode (tests).
-- =============================================================================

CREATE TABLE transfers (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username     VARCHAR(100)   NOT NULL,
    amount       NUMERIC(19, 2) NOT NULL,
    currency     VARCHAR(3)     NOT NULL DEFAULT 'USD',
    description  VARCHAR(255),
    status       VARCHAR(20)    NOT NULL DEFAULT 'COMPLETED',
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_transfers_amount_positive CHECK (amount > 0)
);

CREATE INDEX idx_transfers_username_created_at ON transfers (username, created_at DESC);
