#!/bin/sh
# =============================================================================
# Seed HashiCorp Vault with the secrets the Udapay Ledger Service needs.
#
# Runs once as the `vault-init` compose service (image: hashicorp/vault, so the
# `vault` CLI is available). Idempotent: safe to re-run.
#
# Resulting layout (KV v2 engine mounted at kv/):
#   kv/udapay-ledger/dev
#     spring.datasource.password  <- random value generated by secrets-init
#     spring.datasource.username  <- udapay
#     udapay.ledger.encryption-key <- example of an extra app secret
#
# Spring Cloud Vault (bootstrap.yml: backend=kv, default-context=udapay-ledger,
# profile=dev) reads this path at startup and exposes every key as a Spring
# property, overriding application.yml. That is how the API learns the DB
# password without it ever being committed to the repository.
#
# Manual inspection from the host:
#   export VAULT_ADDR=http://localhost:8200
#   export VAULT_TOKEN=root-token-dev
#   vault kv get kv/udapay-ledger/dev
# =============================================================================
set -eu

VAULT_ADDR="${VAULT_ADDR:-http://vault:8200}"
export VAULT_ADDR
: "${VAULT_TOKEN:?VAULT_TOKEN must be set}"

DB_USER="${POSTGRES_USER:-udapay}"
DB_PASSWORD_FILE="${DB_PASSWORD_FILE:-/run/udapay-secrets/db_password}"
KV_MOUNT="kv"
APP_PATH="udapay-ledger"
PROFILE="${SPRING_PROFILES_ACTIVE:-dev}"

echo "[vault-init] waiting for Vault at ${VAULT_ADDR} ..."
i=0
until vault status >/dev/null 2>&1; do
  i=$((i + 1))
  if [ "$i" -gt 60 ]; then
    echo "[vault-init] Vault did not become ready in time" >&2
    exit 1
  fi
  sleep 1
done

# ---- 1. KV v2 secrets engine at kv/ -----------------------------------------
if vault secrets list -format=json | grep -q "\"${KV_MOUNT}/\""; then
  echo "[vault-init] secrets engine '${KV_MOUNT}/' already enabled"
else
  echo "[vault-init] enabling KV v2 secrets engine at '${KV_MOUNT}/'"
  vault secrets enable -path="${KV_MOUNT}" -version=2 kv
fi

# ---- 2. database credentials --------------------------------------------------
if [ -s "${DB_PASSWORD_FILE}" ]; then
  DB_PASSWORD="$(cat "${DB_PASSWORD_FILE}")"
elif [ -n "${POSTGRES_PASSWORD:-}" ]; then
  DB_PASSWORD="${POSTGRES_PASSWORD}"
else
  echo "[vault-init] no database password available (${DB_PASSWORD_FILE} missing and POSTGRES_PASSWORD unset)" >&2
  exit 1
fi

# An extra application-level secret so the exercise can show rotation of a
# non-database secret too (consumed as property `udapay.ledger.encryption-key`).
ENCRYPTION_KEY="$(head -c 32 /dev/urandom | base64 | tr -d '\n')"

echo "[vault-init] writing ${KV_MOUNT}/${APP_PATH}/${PROFILE}"
vault kv put "${KV_MOUNT}/${APP_PATH}/${PROFILE}" \
  spring.datasource.username="${DB_USER}" \
  spring.datasource.password="${DB_PASSWORD}" \
  udapay.ledger.encryption-key="${ENCRYPTION_KEY}" >/dev/null

# Profile-independent context (read for every profile)
vault kv put "${KV_MOUNT}/${APP_PATH}" \
  udapay.ledger.secrets-source="vault" >/dev/null

echo "[vault-init] stored keys:"
vault kv get -format=json "${KV_MOUNT}/${APP_PATH}/${PROFILE}" \
  | sed -n 's/^ *"\([a-zA-Z0-9._-]*\)": ".*",\{0,1\}$/  - \1/p' | sort -u
echo "[vault-init] done"
